AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager secret containing VMX3 presigner IAM user credentials

Parameters:
  SecretName:
    Type: String
    Default: VMX3PresignerSecret
    Description: Name of the Secrets Manager secret.

  AccessKeyId:
    Type: String
    Description: Access key ID provided by ACES for VMX3 presigner user.

  SecretAccessKey:
    Type: String
    Description: Secret access key provided by ACES for VMX3 presigner user.

Resources:
  VMX3PresignerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: "VMX3 presigner credentials: AccessKeyId + SecretAccessKey"
      SecretString: !Sub |
        {
          "AccessKeyId": "${AccessKeyId}",
          "SecretAccessKey": "${SecretAccessKey}"
        }
      Tags:
        - Key: App
          Value: VMX3
        - Key: KeyRotation
          Value: enabled

Outputs:
  PresignerSecretArn:
    Description: ARN of the VMX3 presigner secret
    Value: !Ref VMX3PresignerSecret
